In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

A:\AI Engineer in the way\ML Projects\Predictive-Maintenance-RUL

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from src.data.loader import DataLoader
from src.data.validator import DataValidator

from src.config.config import (
    TRAIN_DATA_PATH,
    TEST_DATA_PATH,
    RUL_DATA_PATH
)

In [3]:
loader = DataLoader(
    train_path=TRAIN_DATA_PATH,
    test_path=TEST_DATA_PATH,
    rul_path=RUL_DATA_PATH,
)

train_df = loader.load_train()
test_df = loader.load_test()
rul_df = loader.load_rul()

2026-07-22 21:16:05 | INFO | loader.py | Line:18 | Reading train_FD004.txt
2026-07-22 21:16:07 | INFO | loader.py | Line:21 | train_FD004.txt Loaded Successfully
2026-07-22 21:16:07 | INFO | loader.py | Line:18 | Reading test_FD004.txt
2026-07-22 21:16:07 | INFO | loader.py | Line:21 | test_FD004.txt Loaded Successfully
2026-07-22 21:16:07 | INFO | loader.py | Line:18 | Reading RUL_FD004.txt
2026-07-22 21:16:07 | INFO | loader.py | Line:21 | RUL_FD004.txt Loaded Successfully

In [4]:
from src.preprocessing.rul_generator import RULGenerator

generator = RULGenerator(train_df)

raw_df = generator.generate()

raw_df.head()

2026-07-22 21:16:21 | INFO | rul_generator.py | Line:82 | Generating Remaining Useful Life (RUL)...
2026-07-22 21:16:21 | INFO | rul_generator.py | Line:96 | RUL generated successfully.

,unit_number,time_in_cycles,operational_setting_1,operational_setting_2,operational_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,320
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,319
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,318
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,317
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,316

In [5]:
capped_df = generator.generate(cap=125)

2026-07-22 21:16:38 | INFO | rul_generator.py | Line:82 | Generating Remaining Useful Life (RUL)...
2026-07-22 21:16:38 | INFO | rul_generator.py | Line:92 | Applying RUL cap = 125
2026-07-22 21:16:38 | INFO | rul_generator.py | Line:96 | RUL generated successfully.

In [6]:
capped_df.head()

,unit_number,time_in_cycles,operational_setting_1,operational_setting_2,operational_setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21,RUL
0,1,1,42.0049,0.8400,100.0,445.00,549.68,1343.43,1112.93,3.91,...,2387.99,8074.83,9.3335,0.02,330,2212,100.00,10.62,6.3670,125
1,1,2,20.0020,0.7002,100.0,491.19,606.07,1477.61,1237.50,9.35,...,2387.73,8046.13,9.1913,0.02,361,2324,100.00,24.37,14.6552,125
2,1,3,42.0038,0.8409,100.0,445.00,548.95,1343.12,1117.05,3.91,...,2387.97,8066.62,9.4007,0.02,329,2212,100.00,10.48,6.4213,125
3,1,4,42.0000,0.8400,100.0,445.00,548.70,1341.24,1118.03,3.91,...,2388.02,8076.05,9.3369,0.02,328,2212,100.00,10.54,6.4176,125
4,1,5,25.0063,0.6207,60.0,462.54,536.10,1255.23,1033.59,7.05,...,2028.08,7865.80,10.8366,0.02,305,1915,84.93,14.03,8.6754,125